import Head from 'next/head';
import Image from 'next/image';
import Nav from '../components/Nav';

export default function Home() {
  return (
    <div className="bg-softBlack h-screen">
      <Head>
        <title>portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
    </div>
  );
}
